build: off
test_script:
    - gradlew build --no-daemon
after_test:
    - ps: >-
        $wc = New-Object "System.Net.WebClient"

        Get-ChildItem -Path TEST-*.xml |
        Foreach-Object {
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_.FullName))
        }

