version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout

      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}

      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
          key: cache-{{ checksum "build.gradle" }}

      - store_test_results:
          path: hoge/build/test-results
      - store_test_results:
          path: fuga/build/test-results

      - store_artifacts:
          path: hoge/build/reports/tests
      - store_artifacts:
          path: fuga/build/reports/tests

      - run:
          name: create tag
          command: |
              git tag circleci/${CIRCLE_BUILD_NUM}
              git push origin circleci/${CIRCLE_BUILD_NUM}

