version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - add_ssh_keys:
          fingerprints:
              - "24:f0:13:85:75:65:1e:6b:54:39:d1:cd:32:60:62:70"
      
      - checkout

      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}

      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
          key: cache-{{ checksum "build.gradle" }}

      - store_test_results:
          path: hoge/build/test-results
      - store_test_results:
          path: fuga/build/test-results

      - store_artifacts:
          path: hoge/build/reports/tests
      - store_artifacts:
          path: fuga/build/reports/tests

      - run:
          name: create tag
          command: |
              git tag circleci/${CIRCLE_BUILD_NUM}
              git push origin circleci/${CIRCLE_BUILD_NUM}

